#!/bin/sh /etc/rc.common
# Copyright (C) 2019 Tobias Schramm

START=94
STOP=10
USE_PROCD=1

handle_mode()
{
	local mode
	local gpio
	config_get mode "$2" mode
	config_get gpio "$2" "gpio_$1"
	if [ "$mode" == "$1" ] && [ "$3" == on ]; then
		echo 1 > "/sys/class/gpio/$gpio/value"
	elif [ "$3" == off ]; then
		echo 0 > "/sys/class/gpio/$gpio/value"
	fi
}

load_port()
{
	# Load in two steps ensuring only one mode per poe port is enabled
	# at any time
	# First turn off all modes not currently configured
	config_list_foreach "$1" supported_mode handle_mode "$1" off
	# Second turn on the configured mode (if any)
	config_list_foreach "$1" supported_mode handle_mode "$1" on
}

service_triggers()
{
	procd_add_reload_trigger "network"
}

start_service()
{
	if [ -f /etc/config/poe ]; then
		config_load poe
		config_foreach load_port port
	fi
}
